{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-cli",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli-shell-jline3",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.10"
          }
        }
      ],
      "files": [
        {
          "name": "jason-cli-3.3.0.jar",
          "url": "jason-cli-3.3.0.jar",
          "size": 56462,
          "sha512": "07000463e79a46f85fd946dba1fbcf59b907fae42102005e7f93576b07d4c1316d72bfd04dd7ad77c707fba2a76cd6f4ab9aa3711602b06d8eabd085dfaf9272",
          "sha256": "5cc11e0fe41a560170a946fdb2b58f105ae39c0de8db320705a9d2b1bd478678",
          "sha1": "a9675bc0e47c7f5002dc34a90607ceab0f38ddc6",
          "md5": "e97484d91c55369b4eeeb11694527779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli-shell-jline3",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.10"
          }
        }
      ],
      "files": [
        {
          "name": "jason-cli-3.3.0.jar",
          "url": "jason-cli-3.3.0.jar",
          "size": 56462,
          "sha512": "07000463e79a46f85fd946dba1fbcf59b907fae42102005e7f93576b07d4c1316d72bfd04dd7ad77c707fba2a76cd6f4ab9aa3711602b06d8eabd085dfaf9272",
          "sha256": "5cc11e0fe41a560170a946fdb2b58f105ae39c0de8db320705a9d2b1bd478678",
          "sha1": "a9675bc0e47c7f5002dc34a90607ceab0f38ddc6",
          "md5": "e97484d91c55369b4eeeb11694527779"
        }
      ]
    }
  ]
}
