{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0.jar",
          "url": "jason-interpreter-3.3.0.jar",
          "size": 1092994,
          "sha512": "819d6d6706272e13b23613476bc8284989f03cd73e9bff1ce762ec13da2d1d0050b0d6968a0c2c4559400b334f40a1f112bb76a0a5dc2bc2210ee3e5702c11f6",
          "sha256": "05dae8cc72504d1f9b78e828da0e9838810cd7a6d682a4072a50a8ea0d8500e5",
          "sha1": "677d369c59455bf843d859b3e12b1d3fdb10ee03",
          "md5": "fae99c21baab1d7cb443e9deea38785d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0.jar",
          "url": "jason-interpreter-3.3.0.jar",
          "size": 1092994,
          "sha512": "819d6d6706272e13b23613476bc8284989f03cd73e9bff1ce762ec13da2d1d0050b0d6968a0c2c4559400b334f40a1f112bb76a0a5dc2bc2210ee3e5702c11f6",
          "sha256": "05dae8cc72504d1f9b78e828da0e9838810cd7a6d682a4072a50a8ea0d8500e5",
          "sha1": "677d369c59455bf843d859b3e12b1d3fdb10ee03",
          "md5": "fae99c21baab1d7cb443e9deea38785d"
        }
      ]
    }
  ]
}
