{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0.jar",
          "url": "jason-interpreter-3.3.0.jar",
          "size": 1092716,
          "sha512": "2a03958568c8da226afd2af6f0bca4708c1e329725086809ab933744a0a57844d325c851200522b7722baabca2bba818855b749ceba04ba05e8ac8cd6b777810",
          "sha256": "8c6e3dcfec397d111960a81eb90c4de6eebcc0c12d5a36a4a1553a3f36ca8279",
          "sha1": "2b6dee3fe8e14e22fc456564ad45864774b6baf0",
          "md5": "892daa7a0292be9d37168d5a3da74aef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0.jar",
          "url": "jason-interpreter-3.3.0.jar",
          "size": 1092716,
          "sha512": "2a03958568c8da226afd2af6f0bca4708c1e329725086809ab933744a0a57844d325c851200522b7722baabca2bba818855b749ceba04ba05e8ac8cd6b777810",
          "sha256": "8c6e3dcfec397d111960a81eb90c4de6eebcc0c12d5a36a4a1553a3f36ca8279",
          "sha1": "2b6dee3fe8e14e22fc456564ad45864774b6baf0",
          "md5": "892daa7a0292be9d37168d5a3da74aef"
        }
      ]
    }
  ]
}
