{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason",
    "version": "3.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117403,
          "sha512": "d1c940fa84a7db087256eb441cae6a27d909a6568d30b99d3ef462f63d26ed85689ed4e588e5c7ce313968da25e920358d5b2c182392bf18ae28d2fb0954a2ce",
          "sha256": "b6d401e621da55422012e25fb212a1da017643c225b9bf80550043cda2ddecc1",
          "sha1": "c680bf775a37810bc51b11b30e69bf3094c7f178",
          "md5": "d4103c1ee896b5d5fca5b4b5d9322af7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117403,
          "sha512": "d1c940fa84a7db087256eb441cae6a27d909a6568d30b99d3ef462f63d26ed85689ed4e588e5c7ce313968da25e920358d5b2c182392bf18ae28d2fb0954a2ce",
          "sha256": "b6d401e621da55422012e25fb212a1da017643c225b9bf80550043cda2ddecc1",
          "sha1": "c680bf775a37810bc51b11b30e69bf3094c7f178",
          "md5": "d4103c1ee896b5d5fca5b4b5d9322af7"
        }
      ]
    }
  ]
}
