{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "url": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "size": 1084464,
          "sha512": "5c8d31cda69bf4d48e77a7726fda1ebec9e95cbc8afa687583d7df87dead6268e2db80d5ff61fcec9bb046ec174d02f53baf39141c71697f98192302d05a5a74",
          "sha256": "429f70a09796b12405ff2ddf05b2fe290c6e9f6925dc63069559a780d9355113",
          "sha1": "0b45a5a4180688978546b1ae1be870ef2105b993",
          "md5": "e11e7117250a2829c2c9362c6c9c6ece"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "url": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "size": 1084464,
          "sha512": "5c8d31cda69bf4d48e77a7726fda1ebec9e95cbc8afa687583d7df87dead6268e2db80d5ff61fcec9bb046ec174d02f53baf39141c71697f98192302d05a5a74",
          "sha256": "429f70a09796b12405ff2ddf05b2fe290c6e9f6925dc63069559a780d9355113",
          "sha1": "0b45a5a4180688978546b1ae1be870ef2105b993",
          "md5": "e11e7117250a2829c2c9362c6c9c6ece"
        }
      ]
    }
  ]
}
