{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "url": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "size": 1083882,
          "sha512": "eb02d4e9c42ad0b2e835c9aeb94d7f86a1b26f78d78e67fe5d9882cb898709e3cd281cbc4d48fc74dac2626ed9bef56aef8e502be7c2b2f03eabefdf65c5d968",
          "sha256": "3269bed4cf4fb4625f6423650b437bc1452dd3caab8ae045efae7b647654e8e6",
          "sha1": "32b10cfa49832efb3d914d04fa536f221cc1f04f",
          "md5": "08a4155d410f600da1380d76cf5cf275"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "url": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "size": 1083882,
          "sha512": "eb02d4e9c42ad0b2e835c9aeb94d7f86a1b26f78d78e67fe5d9882cb898709e3cd281cbc4d48fc74dac2626ed9bef56aef8e502be7c2b2f03eabefdf65c5d968",
          "sha256": "3269bed4cf4fb4625f6423650b437bc1452dd3caab8ae045efae7b647654e8e6",
          "sha1": "32b10cfa49832efb3d914d04fa536f221cc1f04f",
          "md5": "08a4155d410f600da1380d76cf5cf275"
        }
      ]
    }
  ]
}
