{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "url": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "size": 1083921,
          "sha512": "2f983fc8c0928d08105b8c67a862e12b89ee076c53f39591de576b07438316a8d16798437594f97092dc2f9d508f259ae633df3f6edf4d8c81e1d78ed52235a2",
          "sha256": "797773e81d00cf2ac8ebecc43f8f0acfb248d52b3c628973e86bb90fd6acd6c9",
          "sha1": "57e773743b0c0e8a40a4380f0ea5a66ec5e2da66",
          "md5": "c20bd662b33c6e2d2c42222dced57e22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "url": "jason-interpreter-3.2.1-SNAPSHOT.jar",
          "size": 1083921,
          "sha512": "2f983fc8c0928d08105b8c67a862e12b89ee076c53f39591de576b07438316a8d16798437594f97092dc2f9d508f259ae633df3f6edf4d8c81e1d78ed52235a2",
          "sha256": "797773e81d00cf2ac8ebecc43f8f0acfb248d52b3c628973e86bb90fd6acd6c9",
          "sha1": "57e773743b0c0e8a40a4380f0ea5a66ec5e2da66",
          "md5": "c20bd662b33c6e2d2c42222dced57e22"
        }
      ]
    }
  ]
}
