{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-rest",
    "version": "0.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.7.1-SNAPSHOT.jar",
          "url": "jacamo-rest-0.7.1-SNAPSHOT.jar",
          "size": 59674,
          "sha512": "672d63c62717093c714d98d04974fa050ccaf1d1cef3aff430880b4b446743cc0260d8e11c6186d0bcbf039c28a394fcd7ba2c46dab5750592a6e79927036370",
          "sha256": "07da26d0951334252ba830a81ec0e20a56bfb6a104466710c2111f21e308246e",
          "sha1": "80b1d44aeec04f3b2430e1761fb938347f028e1f",
          "md5": "c78a0bb1b6800b4eb792ff889a6bbd5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.7.1-SNAPSHOT.jar",
          "url": "jacamo-rest-0.7.1-SNAPSHOT.jar",
          "size": 59674,
          "sha512": "672d63c62717093c714d98d04974fa050ccaf1d1cef3aff430880b4b446743cc0260d8e11c6186d0bcbf039c28a394fcd7ba2c46dab5750592a6e79927036370",
          "sha256": "07da26d0951334252ba830a81ec0e20a56bfb6a104466710c2111f21e308246e",
          "sha1": "80b1d44aeec04f3b2430e1761fb938347f028e1f",
          "md5": "c78a0bb1b6800b4eb792ff889a6bbd5a"
        }
      ]
    }
  ]
}
