{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2-SNAPSHOT.jar",
          "url": "jason-3.2-SNAPSHOT.jar",
          "size": 1258098,
          "sha512": "5cb5599bda94f5a288a3c4d8e3999a6667c7bb963c473421cd6b2d6d9bf9fb0a9df0ee5023e3869158b402df84bc1a8f0da335696a39617493bca6b80f601d2b",
          "sha256": "d59f727f4a4500be01d006fc6cf0a69c83bff105361addeae58064c1316ac347",
          "sha1": "ff892201fc0efee85e0d13355d16342eaf70d815",
          "md5": "037bb6f89a64bd306fe660d9d256f3c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2-SNAPSHOT.jar",
          "url": "jason-3.2-SNAPSHOT.jar",
          "size": 1258098,
          "sha512": "5cb5599bda94f5a288a3c4d8e3999a6667c7bb963c473421cd6b2d6d9bf9fb0a9df0ee5023e3869158b402df84bc1a8f0da335696a39617493bca6b80f601d2b",
          "sha256": "d59f727f4a4500be01d006fc6cf0a69c83bff105361addeae58064c1316ac347",
          "sha1": "ff892201fc0efee85e0d13355d16342eaf70d815",
          "md5": "037bb6f89a64bd306fe660d9d256f3c1"
        }
      ]
    }
  ]
}
