{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2-SNAPSHOT.jar",
          "url": "jason-3.2-SNAPSHOT.jar",
          "size": 1120480,
          "sha512": "8db996a0a0546585705ec592ca5720a0799c240e5161b4da9a4778f246696c38c0e505e6f7e585ee79d62eaf69f14ab8c9ec66cf6d8874b59edf7bc7430b6e76",
          "sha256": "a37a51b22d35c190559ed54a7ea0cf10d227a24c94799045cc08330e4f1db47c",
          "sha1": "7fdb4944d2516ce396ad85423f8d8656c5efb597",
          "md5": "1544e6e82e63f542e57027946bf773af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2-SNAPSHOT.jar",
          "url": "jason-3.2-SNAPSHOT.jar",
          "size": 1120480,
          "sha512": "8db996a0a0546585705ec592ca5720a0799c240e5161b4da9a4778f246696c38c0e505e6f7e585ee79d62eaf69f14ab8c9ec66cf6d8874b59edf7bc7430b6e76",
          "sha256": "a37a51b22d35c190559ed54a7ea0cf10d227a24c94799045cc08330e4f1db47c",
          "sha1": "7fdb4944d2516ce396ad85423f8d8656c5efb597",
          "md5": "1544e6e82e63f542e57027946bf773af"
        }
      ]
    }
  ]
}
