{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2-SNAPSHOT.jar",
          "url": "jason-3.2-SNAPSHOT.jar",
          "size": 1251061,
          "sha512": "5ac65b5648a2d2e81110e13767b051f4bbb4d223746302f6c75edbba5d6eef0eed1d1fc91e1f238ebbb5943728c072781a8244d249a68af64877d66587eb6755",
          "sha256": "4ba93835f9693f22c11a76e45a2383214815b55ca49968f9e5600a413158aeba",
          "sha1": "2e379b820b192290cd85361f8a68674fbbdd51b1",
          "md5": "b096c007e10a5c73bf830b06b8f7c147"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2-SNAPSHOT.jar",
          "url": "jason-3.2-SNAPSHOT.jar",
          "size": 1251061,
          "sha512": "5ac65b5648a2d2e81110e13767b051f4bbb4d223746302f6c75edbba5d6eef0eed1d1fc91e1f238ebbb5943728c072781a8244d249a68af64877d66587eb6755",
          "sha256": "4ba93835f9693f22c11a76e45a2383214815b55ca49968f9e5600a413158aeba",
          "sha1": "2e379b820b192290cd85361f8a68674fbbdd51b1",
          "md5": "b096c007e10a5c73bf830b06b8f7c147"
        }
      ]
    }
  ]
}
