{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason",
    "version": "3.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117402,
          "sha512": "fb854d8bf2e7456c639321d6c00c67782231a94c0d3cc9c3758c515cb04825f20a20cac807d8fc228534d6cd9bdcca5b96a67c7cdfaaa187297c9e5eb574a41e",
          "sha256": "82534478d3188d079c50a2ab5dc098fe7a5c96a593bce4161affa6bee4cc2511",
          "sha1": "c0f6fca95fb31d8727efa8be54ce6ee65446566a",
          "md5": "b9057d5cdcd8a8ac1c971431c14ee3bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117402,
          "sha512": "fb854d8bf2e7456c639321d6c00c67782231a94c0d3cc9c3758c515cb04825f20a20cac807d8fc228534d6cd9bdcca5b96a67c7cdfaaa187297c9e5eb574a41e",
          "sha256": "82534478d3188d079c50a2ab5dc098fe7a5c96a593bce4161affa6bee4cc2511",
          "sha1": "c0f6fca95fb31d8727efa8be54ce6ee65446566a",
          "md5": "b9057d5cdcd8a8ac1c971431c14ee3bd"
        }
      ]
    }
  ]
}
