{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason",
    "version": "3.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117404,
          "sha512": "dabe6e0020b9706dcac48ac4fcd59ce61da5c1a6adf75f4bf224f21f7555092c6426980a687bfb40e760b88e02d4a07d17fc0c37dc7cf3ab8b047bd861cde254",
          "sha256": "6f7e046ce4ba55e789f70339c137ec685f7323e4f0e2b20f0f9a0810b648dbcd",
          "sha1": "70a405eebaae6ea4fdc6837b6389f770f0ecb2b4",
          "md5": "99b716440b2d478062f5e6e212267408"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117404,
          "sha512": "dabe6e0020b9706dcac48ac4fcd59ce61da5c1a6adf75f4bf224f21f7555092c6426980a687bfb40e760b88e02d4a07d17fc0c37dc7cf3ab8b047bd861cde254",
          "sha256": "6f7e046ce4ba55e789f70339c137ec685f7323e4f0e2b20f0f9a0810b648dbcd",
          "sha1": "70a405eebaae6ea4fdc6837b6389f770f0ecb2b4",
          "md5": "99b716440b2d478062f5e6e212267408"
        }
      ]
    }
  ]
}
