{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "6ntktaw33rdhthrukox4ckyeme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "6.8.3"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.0.jar",
          "url": "jacamo-1.0.jar",
          "size": 486499,
          "sha512": "b9b6b647751de9dee0c932762fba0de4d6316b2e1851869e899714984b171d356facd1d56a29e85ecde99bb8726f1eeb0a5b2d84efff37f8543f9246dbb05e7e",
          "sha256": "dceb13a1cc8c41c2dd7d19b91f9efa64879756015b89c23e818bc26ad8efb5cf",
          "sha1": "09cd367eb2b452226207dd161eac8086dd015148",
          "md5": "385214b20e3854a36979338822e52cf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "6.8.3"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.0.jar",
          "url": "jacamo-1.0.jar",
          "size": 486499,
          "sha512": "b9b6b647751de9dee0c932762fba0de4d6316b2e1851869e899714984b171d356facd1d56a29e85ecde99bb8726f1eeb0a5b2d84efff37f8543f9246dbb05e7e",
          "sha256": "dceb13a1cc8c41c2dd7d19b91f9efa64879756015b89c23e818bc26ad8efb5cf",
          "sha1": "09cd367eb2b452226207dd161eac8086dd015148",
          "md5": "385214b20e3854a36979338822e52cf2"
        }
      ]
    }
  ]
}
