{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "npl",
    "version": "0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6-SNAPSHOT.jar",
          "url": "npl-0.6-SNAPSHOT.jar",
          "size": 89306,
          "sha512": "1abdccf44116850c4d6df531c77977b6fa49ae215ff7575aca233dc1dc2531f13c5a93896a4e66d06a8ad685b1347a1483f86ca73ba32dd5ab0918fe45e6e325",
          "sha256": "5503170861dd49c0e1c400eeaecd2b4f25f82b5d961fc7ab858344ac1cd61594",
          "sha1": "40efe04faba8f8935d6b23c57861be330674ae45",
          "md5": "40f4a88240461c357cbbf65506bfc39b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6-SNAPSHOT.jar",
          "url": "npl-0.6-SNAPSHOT.jar",
          "size": 89306,
          "sha512": "1abdccf44116850c4d6df531c77977b6fa49ae215ff7575aca233dc1dc2531f13c5a93896a4e66d06a8ad685b1347a1483f86ca73ba32dd5ab0918fe45e6e325",
          "sha256": "5503170861dd49c0e1c400eeaecd2b4f25f82b5d961fc7ab858344ac1cd61594",
          "sha1": "40efe04faba8f8935d6b23c57861be330674ae45",
          "md5": "40f4a88240461c357cbbf65506bfc39b"
        }
      ]
    }
  ]
}
