{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "npl",
    "version": "0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6-SNAPSHOT.jar",
          "url": "npl-0.6-SNAPSHOT.jar",
          "size": 87921,
          "sha512": "03d5fd62b0684f77edaf4ff86fc959d8d2c420d74de86ccbd6e1cf6ffc9f5c829d9b014e647d7b77fc6b46530fb81e53e8ff1eda5df32197d47c223451b996c6",
          "sha256": "b2b4125d91fb5d8647265172d2f9eea897455f467060349991360dac57c72ece",
          "sha1": "3acf9f39524706594da39ef4c83433b4a2b5c108",
          "md5": "367c5216265b3d4b35f793f1b4b8ef8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6-SNAPSHOT.jar",
          "url": "npl-0.6-SNAPSHOT.jar",
          "size": 87921,
          "sha512": "03d5fd62b0684f77edaf4ff86fc959d8d2c420d74de86ccbd6e1cf6ffc9f5c829d9b014e647d7b77fc6b46530fb81e53e8ff1eda5df32197d47c223451b996c6",
          "sha256": "b2b4125d91fb5d8647265172d2f9eea897455f467060349991360dac57c72ece",
          "sha1": "3acf9f39524706594da39ef4c83433b4a2b5c108",
          "md5": "367c5216265b3d4b35f793f1b4b8ef8f"
        }
      ]
    }
  ]
}
