{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "npl",
    "version": "0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.2.2"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6-SNAPSHOT.jar",
          "url": "npl-0.6-SNAPSHOT.jar",
          "size": 91214,
          "sha512": "f34d4a25a7653965ef7d25e95cc5a373be2990a9d2902ecb1659def0f6fa13d9a65e05c2e025dd1e3112e885485126b7eb480d9eef92238db5e20a1650a4a671",
          "sha256": "34ad3d1d4243fa4e714584fd784deefe8cc87a09be2ef11a01abf1080e910050",
          "sha1": "d9a5c55a7daf8002fa3ed18982b1629a3ddf0de8",
          "md5": "21e0fcf1d852bd76f0c6d4f2a29a6f59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.2.2"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6-SNAPSHOT.jar",
          "url": "npl-0.6-SNAPSHOT.jar",
          "size": 91214,
          "sha512": "f34d4a25a7653965ef7d25e95cc5a373be2990a9d2902ecb1659def0f6fa13d9a65e05c2e025dd1e3112e885485126b7eb480d9eef92238db5e20a1650a4a671",
          "sha256": "34ad3d1d4243fa4e714584fd784deefe8cc87a09be2ef11a01abf1080e910050",
          "sha1": "d9a5c55a7daf8002fa3ed18982b1629a3ddf0de8",
          "md5": "21e0fcf1d852bd76f0c6d4f2a29a6f59"
        }
      ]
    }
  ]
}
