{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ktfx4t7sirhobgvzjnejnejzpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.1-SNAPSHOT.jar",
          "url": "jason-3.1-SNAPSHOT.jar",
          "size": 1199761,
          "sha512": "c05a09254575f2f2427a22f336e0f0000b99e8e52c8d97465064b93dec0d23b19c56a0e7d8a999ac59cd11143551f5e1e1c0a353714ddadb034236d3a49df28d",
          "sha256": "3658e13e92b3a3a020ea878e9a71d7e2558e8d8c29f1e7bfd8751e7193231de4",
          "sha1": "53f5364348802e5469111fcdc8ed7d938b23b30c",
          "md5": "161ce40e7921f0a784cb1c463471b8a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.1-SNAPSHOT.jar",
          "url": "jason-3.1-SNAPSHOT.jar",
          "size": 1199761,
          "sha512": "c05a09254575f2f2427a22f336e0f0000b99e8e52c8d97465064b93dec0d23b19c56a0e7d8a999ac59cd11143551f5e1e1c0a353714ddadb034236d3a49df28d",
          "sha256": "3658e13e92b3a3a020ea878e9a71d7e2558e8d8c29f1e7bfd8751e7193231de4",
          "sha1": "53f5364348802e5469111fcdc8ed7d938b23b30c",
          "md5": "161ce40e7921f0a784cb1c463471b8a3"
        }
      ]
    }
  ]
}
