{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iwcwww5jevhgtpyvartfdyy444"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.1-SNAPSHOT.jar",
          "url": "jason-3.1-SNAPSHOT.jar",
          "size": 1195737,
          "sha512": "60123fc9134d4ad795176a50ecd91907705465f211796dbfa39af9710133acb98bc1385abc2fbcc580c80b2af2d59503a064f561e46c1d36065a14028159f594",
          "sha256": "c016945fe01c275c9d0a556bb18d29f407334b86394a05b53e0b94e0733cb82f",
          "sha1": "bac81a82ad62e744b504f78f1ed93c38de99212c",
          "md5": "a53670c233111e5896393183ca5994cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.1-SNAPSHOT.jar",
          "url": "jason-3.1-SNAPSHOT.jar",
          "size": 1195737,
          "sha512": "60123fc9134d4ad795176a50ecd91907705465f211796dbfa39af9710133acb98bc1385abc2fbcc580c80b2af2d59503a064f561e46c1d36065a14028159f594",
          "sha256": "c016945fe01c275c9d0a556bb18d29f407334b86394a05b53e0b94e0733cb82f",
          "sha1": "bac81a82ad62e744b504f78f1ed93c38de99212c",
          "md5": "a53670c233111e5896393183ca5994cf"
        }
      ]
    }
  ]
}
