{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.4-SNAPSHOT.jar",
          "url": "sai-0.5.4-SNAPSHOT.jar",
          "size": 312378,
          "sha512": "fe1f56210d1305762887d898a3acfaa765126ad0ca4b1791b7137f42461589962d13f32b76ab5b8f075d185e0108a75168949149196db381a36dd2e1a3e2dba9",
          "sha256": "de34570b1cfb680154a94a6ac9555c873b7e0fc8db5624ca2e8881931eb6b741",
          "sha1": "2bc573c937e1494bb2c96a948fc2c28732145fcb",
          "md5": "4f16454c9532e162693b72c3d3e404f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.4-SNAPSHOT.jar",
          "url": "sai-0.5.4-SNAPSHOT.jar",
          "size": 312378,
          "sha512": "fe1f56210d1305762887d898a3acfaa765126ad0ca4b1791b7137f42461589962d13f32b76ab5b8f075d185e0108a75168949149196db381a36dd2e1a3e2dba9",
          "sha256": "de34570b1cfb680154a94a6ac9555c873b7e0fc8db5624ca2e8881931eb6b741",
          "sha1": "2bc573c937e1494bb2c96a948fc2c28732145fcb",
          "md5": "4f16454c9532e162693b72c3d3e404f1"
        }
      ]
    }
  ]
}
