{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.4-SNAPSHOT.jar",
          "url": "sai-0.5.4-SNAPSHOT.jar",
          "size": 312416,
          "sha512": "5b6bcbf7cc1c9600344ace012900a3c74a83aec59d3682c286481c3944bb7caa86c71e57fa8a09468668cf20959b43d08da50d0139334e2bfed6e79687f657ed",
          "sha256": "50eb6b5b9298715a7bc9ba5ebd570399f95f1f4735685ce191d3e49cd2cafc2f",
          "sha1": "9508a26be9d713eae257028de4d0a2389918d32b",
          "md5": "123fc736a9d2e48f293227c0dcf8f954"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.4-SNAPSHOT.jar",
          "url": "sai-0.5.4-SNAPSHOT.jar",
          "size": 312416,
          "sha512": "5b6bcbf7cc1c9600344ace012900a3c74a83aec59d3682c286481c3944bb7caa86c71e57fa8a09468668cf20959b43d08da50d0139334e2bfed6e79687f657ed",
          "sha256": "50eb6b5b9298715a7bc9ba5ebd570399f95f1f4735685ce191d3e49cd2cafc2f",
          "sha1": "9508a26be9d713eae257028de4d0a2389918d32b",
          "md5": "123fc736a9d2e48f293227c0dcf8f954"
        }
      ]
    }
  ]
}
