{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.4-SNAPSHOT.jar",
          "url": "sai-0.5.4-SNAPSHOT.jar",
          "size": 312375,
          "sha512": "639c7b05ad00490da61a7cc940309c09bb18a2d18a834922cff1dcc09aecc7371d4ac187de60a222ddaf652af5089fa135199bd79f24347eb8ca17867a317b1c",
          "sha256": "5ce0a30a84fc8e165c7354ffcd1035ba5d2074cd24c5b25d21ead35d12042167",
          "sha1": "4f2023ff727544e5e9c0e4caa1a4c070adbc02c5",
          "md5": "0b2edf80405893e8c3a6337db87d89cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.4-SNAPSHOT.jar",
          "url": "sai-0.5.4-SNAPSHOT.jar",
          "size": 312375,
          "sha512": "639c7b05ad00490da61a7cc940309c09bb18a2d18a834922cff1dcc09aecc7371d4ac187de60a222ddaf652af5089fa135199bd79f24347eb8ca17867a317b1c",
          "sha256": "5ce0a30a84fc8e165c7354ffcd1035ba5d2074cd24c5b25d21ead35d12042167",
          "sha1": "4f2023ff727544e5e9c0e4caa1a4c070adbc02c5",
          "md5": "0b2edf80405893e8c3a6337db87d89cd"
        }
      ]
    }
  ]
}
