{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.2.jar",
          "url": "jason-interpreter-3.3.2.jar",
          "size": 1092166,
          "sha512": "bc2c6fa91fa10eb3c3b5671f6a3c9cdea139bd799f9450082ba64263611d23dbd0c2b3c4b21e0cca0ccf99945dc6a31fa1ffd5b8d6d7b9526efe125ef2a848c6",
          "sha256": "cd79268ddcfa45599284bda64bd6980dbd86eec6c862028cc276495aab49154c",
          "sha1": "a61909ae79063a23ae6e42768f07d4c3ed849a40",
          "md5": "fad020c328abc27502e8d8eb3ea8d20c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.2.jar",
          "url": "jason-interpreter-3.3.2.jar",
          "size": 1092166,
          "sha512": "bc2c6fa91fa10eb3c3b5671f6a3c9cdea139bd799f9450082ba64263611d23dbd0c2b3c4b21e0cca0ccf99945dc6a31fa1ffd5b8d6d7b9526efe125ef2a848c6",
          "sha256": "cd79268ddcfa45599284bda64bd6980dbd86eec6c862028cc276495aab49154c",
          "sha1": "a61909ae79063a23ae6e42768f07d4c3ed849a40",
          "md5": "fad020c328abc27502e8d8eb3ea8d20c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jason-interpreter-3.3.2-javadoc.jar",
          "url": "jason-interpreter-3.3.2-javadoc.jar",
          "size": 1696576,
          "sha512": "0c593b74f4358ad663396af555c40481bab3d5738187ab51edd64ad00a87b1e757b797869d7a14332dbdf0985c63934097081d0bcadbad2103dfd908207ecf2a",
          "sha256": "ed44719d6ad53c69179ff6882ca102e7cdc47bf12b29b32aad3aab694a00e5da",
          "sha1": "948d602cc876ed91887187b7711938fc575667fa",
          "md5": "5b70ca807eecdec61e4169bb2f155a3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jason-interpreter-3.3.2-sources.jar",
          "url": "jason-interpreter-3.3.2-sources.jar",
          "size": 653186,
          "sha512": "4f428fd89d1b13c2feea7dd063dff87d366f1bf415decbd71cfe80af56fe6acdaf1a84e529d7979999c6b17b568663a54f87d9dc7c5a7a83a67bbc6f021a4640",
          "sha256": "2f4e450d1fb116a9bf2d4ab7eddb2265b82fa4a303a97a64570c67710e2d1ce0",
          "sha1": "ee7ffcdcc484376d9714da857cb8e6460ca34541",
          "md5": "b6ceaaf1e3ae9bc4304839b9233f0d76"
        }
      ]
    }
  ]
}
