{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.2.jar",
          "url": "jason-interpreter-3.3.2.jar",
          "size": 1094358,
          "sha512": "71c25e06233a4ecd3ee4559a785d8f0a74f0eb78084a6f74a54891975e4e654a4e368d140ce242840617a25552ed9e58dcd58b04328b64351b133d58bbd1515e",
          "sha256": "b89bf400070f997602f3259ceea82c48bbb5dd7725e63518c1a403e002482d12",
          "sha1": "d9a11151ea2bdb76a0246dbecb54aeb448366746",
          "md5": "10fda79cf590203b5bad27f7d3beb1d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.2.jar",
          "url": "jason-interpreter-3.3.2.jar",
          "size": 1094358,
          "sha512": "71c25e06233a4ecd3ee4559a785d8f0a74f0eb78084a6f74a54891975e4e654a4e368d140ce242840617a25552ed9e58dcd58b04328b64351b133d58bbd1515e",
          "sha256": "b89bf400070f997602f3259ceea82c48bbb5dd7725e63518c1a403e002482d12",
          "sha1": "d9a11151ea2bdb76a0246dbecb54aeb448366746",
          "md5": "10fda79cf590203b5bad27f7d3beb1d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jason-interpreter-3.3.2-javadoc.jar",
          "url": "jason-interpreter-3.3.2-javadoc.jar",
          "size": 1697202,
          "sha512": "6a18a1492723aac9b0ad8538cd67d288060fa4c12c6d3930beaf409f4821890dc31628f13d703188ee2a666419da13afa7b7028d36bb740eb665a7636de30879",
          "sha256": "07ec2a45a1abe855f384a4b9b2c3a2ea95bc1180e25e0d37959baa010ecb592d",
          "sha1": "6029d2e1fc677f9f11502bd6304081af6c220b31",
          "md5": "26c7147b4622117e5acb7a71d55a4837"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jason-interpreter-3.3.2-sources.jar",
          "url": "jason-interpreter-3.3.2-sources.jar",
          "size": 653506,
          "sha512": "00d2bdea2a91c274f6402f09d3c32914c2f13a8a4544b1fec1b62d039f0a2e004cdc361ef5eab32c70860f472a9d75a76cfca86d536cef7751825c752752d46d",
          "sha256": "de04f8017fa0304ad447db498f913ade1d33e207e625c35e5c63ea4d2094fb87",
          "sha1": "26045b40fd41285dd736ed11d8a946165ef31288",
          "md5": "60d0113c923de2dee76c07a8011d3396"
        }
      ]
    }
  ]
}
