{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0.jar",
          "url": "jason-3.2.0.jar",
          "size": 1117340,
          "sha512": "b048263b60cb7c5d65d090f6ec4f9797dfab26fab70f4d979c2b27a51a4a181d9d0430283beea99df1ef8e3f9d935c738d8126bb40510849c7bb7b678c7bfad8",
          "sha256": "b1ff7ff6230e1c81cf6f2ed1ebfbcaf2558dfacb964b02c3caf978b202523c61",
          "sha1": "70c5c8b5f026ce5fcbdda164d98325b68264ec58",
          "md5": "55e42fc3cfa64b52e4858f42bb84a126"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0.jar",
          "url": "jason-3.2.0.jar",
          "size": 1117340,
          "sha512": "b048263b60cb7c5d65d090f6ec4f9797dfab26fab70f4d979c2b27a51a4a181d9d0430283beea99df1ef8e3f9d935c738d8126bb40510849c7bb7b678c7bfad8",
          "sha256": "b1ff7ff6230e1c81cf6f2ed1ebfbcaf2558dfacb964b02c3caf978b202523c61",
          "sha1": "70c5c8b5f026ce5fcbdda164d98325b68264ec58",
          "md5": "55e42fc3cfa64b52e4858f42bb84a126"
        }
      ]
    }
  ]
}
