{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0.jar",
          "url": "jason-3.2.0.jar",
          "size": 1117340,
          "sha512": "185f9296dc42b3cb6a35d43b4b69d9b131787a54295668c4d9ef537058e9c9c970d50d0354c4f51b69851a63e5a542915d9d5b53d80fa4956f2162c26013cb7b",
          "sha256": "b97c49745df1a732479bf9b6ce963ee2050f9cb3e9283187cd6fc41e81681fe8",
          "sha1": "88bc1fe98ac3e1ba81446defe739f850ffcc2028",
          "md5": "e4933fbcf4295b3e01e40820307447fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0.jar",
          "url": "jason-3.2.0.jar",
          "size": 1117340,
          "sha512": "185f9296dc42b3cb6a35d43b4b69d9b131787a54295668c4d9ef537058e9c9c970d50d0354c4f51b69851a63e5a542915d9d5b53d80fa4956f2162c26013cb7b",
          "sha256": "b97c49745df1a732479bf9b6ce963ee2050f9cb3e9283187cd6fc41e81681fe8",
          "sha1": "88bc1fe98ac3e1ba81446defe739f850ffcc2028",
          "md5": "e4933fbcf4295b3e01e40820307447fc"
        }
      ]
    }
  ]
}
