{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason",
    "version": "3.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117402,
          "sha512": "14b73156d1d70406c16bc17cb2ea5f93d11146524ca47c67df8a83b1b7459029bb14ce938f0c5334e3d4a51d7b303cbd300bbdc1749d359c3988285d539160d1",
          "sha256": "7a7f218f921018990de1cc6c8bd0a1602c7a307493a520eea5daabad24a576d9",
          "sha1": "54acc0fdf6e00a4ee632cb15c04e3616bd663a1a",
          "md5": "1bcf96a295031a6d4d0409d07793de8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.2.0-SNAPSHOT.jar",
          "url": "jason-3.2.0-SNAPSHOT.jar",
          "size": 1117402,
          "sha512": "14b73156d1d70406c16bc17cb2ea5f93d11146524ca47c67df8a83b1b7459029bb14ce938f0c5334e3d4a51d7b303cbd300bbdc1749d359c3988285d539160d1",
          "sha256": "7a7f218f921018990de1cc6c8bd0a1602c7a307493a520eea5daabad24a576d9",
          "sha1": "54acc0fdf6e00a4ee632cb15c04e3616bd663a1a",
          "md5": "1bcf96a295031a6d4d0409d07793de8a"
        }
      ]
    }
  ]
}
