{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-rest",
    "version": "0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "7kevnrefwzbnbli3g7vmtarp2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.7-SNAPSHOT.jar",
          "url": "jacamo-rest-0.7-SNAPSHOT.jar",
          "size": 57958,
          "sha512": "78b934e985008d8266a68ae5892a70a9360e924f627991e09826b4fd27917891ef6fd61529bdf2b24d29233b37f3c1809b6c3af6bfe1eb00592bd1bcd82be3a2",
          "sha256": "439dcbce2e32ed50f447a8032154a5277b19fea7ac72d5b02e0e12c72d0f43d5",
          "sha1": "808713072acf8b1171ca694fae2ee4274f759140",
          "md5": "ca36127c63b1e1e914be89f56dc39355"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.7-SNAPSHOT.jar",
          "url": "jacamo-rest-0.7-SNAPSHOT.jar",
          "size": 57958,
          "sha512": "78b934e985008d8266a68ae5892a70a9360e924f627991e09826b4fd27917891ef6fd61529bdf2b24d29233b37f3c1809b6c3af6bfe1eb00592bd1bcd82be3a2",
          "sha256": "439dcbce2e32ed50f447a8032154a5277b19fea7ac72d5b02e0e12c72d0f43d5",
          "sha1": "808713072acf8b1171ca694fae2ee4274f759140",
          "md5": "ca36127c63b1e1e914be89f56dc39355"
        }
      ]
    }
  ]
}
