{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "npl",
    "version": "0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6.jar",
          "url": "npl-0.6.jar",
          "size": 90774,
          "sha512": "32c53f36e8755e1bd0b3967c3ddd63649e7e52438006b2ce0396cf64bbe58d0e5cc893a739cdfededcc38869dedd4f3b063a4e7930207a1d27cfcb6fe859c2b5",
          "sha256": "fdf43a2cec55145fd31531c5eda95fa96c6440322887d2ff3b0598da3f2f1d43",
          "sha1": "67f9000e8f90c6f09b5726bfb3fafec4e9c4bda9",
          "md5": "020f5614a7e1470b81839d333786938b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6.jar",
          "url": "npl-0.6.jar",
          "size": 90774,
          "sha512": "32c53f36e8755e1bd0b3967c3ddd63649e7e52438006b2ce0396cf64bbe58d0e5cc893a739cdfededcc38869dedd4f3b063a4e7930207a1d27cfcb6fe859c2b5",
          "sha256": "fdf43a2cec55145fd31531c5eda95fa96c6440322887d2ff3b0598da3f2f1d43",
          "sha1": "67f9000e8f90c6f09b5726bfb3fafec4e9c4bda9",
          "md5": "020f5614a7e1470b81839d333786938b"
        }
      ]
    }
  ]
}
