{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "moise",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "xml-apis",
              "module": "xml-apis-ext"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moise-1.1-SNAPSHOT.jar",
          "url": "moise-1.1-SNAPSHOT.jar",
          "size": 340666,
          "sha512": "2062e064144ddb9d1ab1d2cb2a9ce54e9c777355ce2aa3d2be48ae1a4e55b73188f3ab464fa00f77981645c4614e95a39955db46f3886c94b4c7d3c55da53e1f",
          "sha256": "de9f8dedfb4782a5cfcd39de9cfc87e7f0f4e3575fbe7e230d3dbb49caf4bd94",
          "sha1": "24b654f5fc13b68e23feae809508c2556d95b01f",
          "md5": "38b5b56e91c9c75f6b0de266be36919b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "xml-apis",
              "module": "xml-apis-ext"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moise-1.1-SNAPSHOT.jar",
          "url": "moise-1.1-SNAPSHOT.jar",
          "size": 340666,
          "sha512": "2062e064144ddb9d1ab1d2cb2a9ce54e9c777355ce2aa3d2be48ae1a4e55b73188f3ab464fa00f77981645c4614e95a39955db46f3886c94b4c7d3c55da53e1f",
          "sha256": "de9f8dedfb4782a5cfcd39de9cfc87e7f0f4e3575fbe7e230d3dbb49caf4bd94",
          "sha1": "24b654f5fc13b68e23feae809508c2556d95b01f",
          "md5": "38b5b56e91c9c75f6b0de266be36919b"
        }
      ]
    }
  ]
}
