{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "moise",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "xml-apis",
              "module": "xml-apis-ext"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moise-1.1-SNAPSHOT.jar",
          "url": "moise-1.1-SNAPSHOT.jar",
          "size": 340581,
          "sha512": "d6bdafb042e0ae8ff9b0844556bde534ad6f7e2bece7149167b8e26544b6a34385b0236ef1e073deb9487f1ed4d1cf544378e8bb445e9de70ba7978c859300ac",
          "sha256": "ae08b4aa253d9800b913bfb1a43969eb503645854adec3bddb040f265bf5829c",
          "sha1": "26c9941d6add41c4093bc7602070dd0ccc7691ec",
          "md5": "5daf87256c4d2af5244a3d3ec5bc56ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "xml-apis",
              "module": "xml-apis-ext"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moise-1.1-SNAPSHOT.jar",
          "url": "moise-1.1-SNAPSHOT.jar",
          "size": 340581,
          "sha512": "d6bdafb042e0ae8ff9b0844556bde534ad6f7e2bece7149167b8e26544b6a34385b0236ef1e073deb9487f1ed4d1cf544378e8bb445e9de70ba7978c859300ac",
          "sha256": "ae08b4aa253d9800b913bfb1a43969eb503645854adec3bddb040f265bf5829c",
          "sha1": "26c9941d6add41c4093bc7602070dd0ccc7691ec",
          "md5": "5daf87256c4d2af5244a3d3ec5bc56ee"
        }
      ]
    }
  ]
}
