{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "moise",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "xml-apis",
              "module": "xml-apis-ext"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moise-1.1-SNAPSHOT.jar",
          "url": "moise-1.1-SNAPSHOT.jar",
          "size": 340541,
          "sha512": "184a8c0b3b3dec188919dff9d74c16b23e6bc763a8d853930dc5fe3270adb1d2024cd38bb6fa5a3f8dc16fbb7de5810a1ff22ab7b7cd19784e9958981d229b3b",
          "sha256": "a2c835bd6b5ba83be12ea1c1eb7106e6e3669003fedfa3efb75b45accf8a3fb2",
          "sha1": "2ce72e1afbaa8cec0346ed35fc1dd56a547d6574",
          "md5": "776b84eb1a68b4fd7bce8d2431e063d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "xml-apis",
              "module": "xml-apis-ext"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moise-1.1-SNAPSHOT.jar",
          "url": "moise-1.1-SNAPSHOT.jar",
          "size": 340541,
          "sha512": "184a8c0b3b3dec188919dff9d74c16b23e6bc763a8d853930dc5fe3270adb1d2024cd38bb6fa5a3f8dc16fbb7de5810a1ff22ab7b7cd19784e9958981d229b3b",
          "sha256": "a2c835bd6b5ba83be12ea1c1eb7106e6e3669003fedfa3efb75b45accf8a3fb2",
          "sha1": "2ce72e1afbaa8cec0346ed35fc1dd56a547d6574",
          "md5": "776b84eb1a68b4fd7bce8d2431e063d4"
        }
      ]
    }
  ]
}
