{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-rest",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "wmmtovyrqfcgtjiimeynrk55ey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jacamo-rest-0.5-SNAPSHOT.jar",
          "url": "jacamo-rest-0.5-SNAPSHOT.jar",
          "size": 52035,
          "sha512": "de67ed9b5f85953d2dcbe427523586c1ffb7421d3780ebaed5c12c10f3f38d47101c2c265975331abed577ec5edc95e3278fe5addc8fb2380fc74c030a2e7328",
          "sha256": "2a6bf094d2591f09d32bf09451fa6bd6716e7b44c947e98cdeae6e823d98ea85",
          "sha1": "d47881156130e3c948c182314e0abe83df9027a8",
          "md5": "3861e1a5de134f92f776be55d9d46943"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "0.9-SNAPSHOT"
          }
        },
        {
          "group": "org.jason-lang",
          "module": "jason",
          "version": {
            "requires": "2.5-SNAPSHOT"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.apache.zookeeper",
          "module": "zookeeper",
          "version": {
            "requires": "3.5.4-beta"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-framework",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-x-async",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.5-SNAPSHOT.jar",
          "url": "jacamo-rest-0.5-SNAPSHOT.jar",
          "size": 52035,
          "sha512": "de67ed9b5f85953d2dcbe427523586c1ffb7421d3780ebaed5c12c10f3f38d47101c2c265975331abed577ec5edc95e3278fe5addc8fb2380fc74c030a2e7328",
          "sha256": "2a6bf094d2591f09d32bf09451fa6bd6716e7b44c947e98cdeae6e823d98ea85",
          "sha1": "d47881156130e3c948c182314e0abe83df9027a8",
          "md5": "3861e1a5de134f92f776be55d9d46943"
        }
      ]
    }
  ]
}
