{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "interpreter",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "interpreter-3.2.0.jar",
          "url": "interpreter-3.2.0.jar",
          "size": 1117340,
          "sha512": "55c337255ced1ed51df7ce73793b6679db1ba3beb3ae0bbe3ad0c79450865aa4b54c879e0894c65a7d4d1ebc32517128c864a28782cb2a0adfac8839c31c0568",
          "sha256": "420a293671462c581a4d824201e255c84bf791b18def8365410fe45057f1d784",
          "sha1": "2a03d3284a30845bd279869436a801f5e921ff35",
          "md5": "e789e1f38fcce4e24cb0c6a01223a2db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "interpreter-3.2.0.jar",
          "url": "interpreter-3.2.0.jar",
          "size": 1117340,
          "sha512": "55c337255ced1ed51df7ce73793b6679db1ba3beb3ae0bbe3ad0c79450865aa4b54c879e0894c65a7d4d1ebc32517128c864a28782cb2a0adfac8839c31c0568",
          "sha256": "420a293671462c581a4d824201e255c84bf791b18def8365410fe45057f1d784",
          "sha1": "2a03d3284a30845bd279869436a801f5e921ff35",
          "md5": "e789e1f38fcce4e24cb0c6a01223a2db"
        }
      ]
    }
  ]
}
