{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "url": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "size": 1092051,
          "sha512": "989ea022c29ddaff3146f08e8b91a16d3a09670caec716bc70481270042da836b53187bbd0f0511d9b86da8cb3e7f437d028c17c81aa3dc0614b1b2f24249eb1",
          "sha256": "8e0b3fa2e42aa198f1204791f42c508ecef97619711ee3c2a322925ff123eefa",
          "sha1": "d14105cee87716b30fedcc87fc554ae23d615e63",
          "md5": "aa9890a23d53405f0190a630eafd2385"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "url": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "size": 1092051,
          "sha512": "989ea022c29ddaff3146f08e8b91a16d3a09670caec716bc70481270042da836b53187bbd0f0511d9b86da8cb3e7f437d028c17c81aa3dc0614b1b2f24249eb1",
          "sha256": "8e0b3fa2e42aa198f1204791f42c508ecef97619711ee3c2a322925ff123eefa",
          "sha1": "d14105cee87716b30fedcc87fc554ae23d615e63",
          "md5": "aa9890a23d53405f0190a630eafd2385"
        }
      ]
    }
  ]
}
