{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "url": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "size": 1084705,
          "sha512": "470d7a2da44de3ca8e2e31f33cbb26ce2e143804527ba49c4451820e65e1b7ac4c947319d938be7a99fb67ab46b21026a176edd6c7d7da57bb828cd4d84d5cfc",
          "sha256": "327b9bba82a821551edf74de7b51d7bfd38628aea095c83953ca16d7360f8082",
          "sha1": "62431c6c916637cb1f10bb3232fb856e51899b38",
          "md5": "3ff0b60b55ae8c8773ee16a613825719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "url": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "size": 1084705,
          "sha512": "470d7a2da44de3ca8e2e31f33cbb26ce2e143804527ba49c4451820e65e1b7ac4c947319d938be7a99fb67ab46b21026a176edd6c7d7da57bb828cd4d84d5cfc",
          "sha256": "327b9bba82a821551edf74de7b51d7bfd38628aea095c83953ca16d7360f8082",
          "sha1": "62431c6c916637cb1f10bb3232fb856e51899b38",
          "md5": "3ff0b60b55ae8c8773ee16a613825719"
        }
      ]
    }
  ]
}
