{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "url": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "size": 1085256,
          "sha512": "ad1500816b57a3256e4fa1d4da621f5ceaaa22a41e126c8bb7ae07ca4a4d5df873b24ec4f24b704975d92597e0b55ac55488d9b63c7a4e21eeb07f840837ebe0",
          "sha256": "662d93900c1d9b274a49d60316f3625e56641865af454114bec99715462cd66c",
          "sha1": "58c4a8b72460c58278c860c6a7846e8d945e5aa5",
          "md5": "3f61e79e98b0c9f511585bace301cfc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "url": "jason-interpreter-3.3.0-SNAPSHOT.jar",
          "size": 1085256,
          "sha512": "ad1500816b57a3256e4fa1d4da621f5ceaaa22a41e126c8bb7ae07ca4a4d5df873b24ec4f24b704975d92597e0b55ac55488d9b63c7a4e21eeb07f840837ebe0",
          "sha256": "662d93900c1d9b274a49d60316f3625e56641865af454114bec99715462cd66c",
          "sha1": "58c4a8b72460c58278c860c6a7846e8d945e5aa5",
          "md5": "3f61e79e98b0c9f511585bace301cfc2"
        }
      ]
    }
  ]
}
