{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.1.jar",
          "url": "jason-interpreter-3.3.1.jar",
          "size": 1094077,
          "sha512": "5a5ff972d69f49e54c80501d68c71c3d41d39d139be8f91c94d215951d1ecfec31304d3230cad648f383cdf38d89aa59d952c3440c4fc3da7d7fca3d9ae5008b",
          "sha256": "df9314b7047398384997c2ff14070ff92f1b68c9fcc6ea98b2a44d0d58583e09",
          "sha1": "c2f76d5f1ca092f8be036eda4962fa41891f4854",
          "md5": "eb1d957ce6c9218b5d1df5ebd788ebd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.3.1.jar",
          "url": "jason-interpreter-3.3.1.jar",
          "size": 1094077,
          "sha512": "5a5ff972d69f49e54c80501d68c71c3d41d39d139be8f91c94d215951d1ecfec31304d3230cad648f383cdf38d89aa59d952c3440c4fc3da7d7fca3d9ae5008b",
          "sha256": "df9314b7047398384997c2ff14070ff92f1b68c9fcc6ea98b2a44d0d58583e09",
          "sha1": "c2f76d5f1ca092f8be036eda4962fa41891f4854",
          "md5": "eb1d957ce6c9218b5d1df5ebd788ebd7"
        }
      ]
    }
  ]
}
