{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.3.jar",
          "url": "sai-0.5.3.jar",
          "size": 319595,
          "sha512": "e8f1e230346592c553ffc78ca3b95e6cc7cd927828f77f0575a2a3f8e12862bbde712eab7aab7dc4c80073b17c81f83a6141d466ea7b56596580c2e64a9cc828",
          "sha256": "e112fad4086b824b6972f16d948ad5720e91a285d4706302106f51b09b87e4ae",
          "sha1": "706e350d863fb560b1542662c2dda046d758ef49",
          "md5": "f62c5527de2d805a46204b092bb8aef8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5.3.jar",
          "url": "sai-0.5.3.jar",
          "size": 319595,
          "sha512": "e8f1e230346592c553ffc78ca3b95e6cc7cd927828f77f0575a2a3f8e12862bbde712eab7aab7dc4c80073b17c81f83a6141d466ea7b56596580c2e64a9cc828",
          "sha256": "e112fad4086b824b6972f16d948ad5720e91a285d4706302106f51b09b87e4ae",
          "sha1": "706e350d863fb560b1542662c2dda046d758ef49",
          "md5": "f62c5527de2d805a46204b092bb8aef8"
        }
      ]
    }
  ]
}
