{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "2.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "z6jtussx4vbybn7g2i4idqlr3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "jason-2.6.3-SNAPSHOT.jar",
          "url": "jason-2.6.3-SNAPSHOT.jar",
          "size": 1156158,
          "sha512": "10626e38366c46f8240ea92d46f0fb7872d8bf11ab9c8c11a9f57c90bc04bef4a56cfb446252fc104884c9da157cad2eeeac6e0efe496666cc99122ff1b8e298",
          "sha256": "fdd82c6db40154d2fee81cad24b68f4c152a12b0795016116933838b0c467de6",
          "sha1": "fd6be0754948c82f6d1e85cad2639728fdcdee84",
          "md5": "b49d85b07c6b47fa9fa93dc3ed82353e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "jason-2.6.3-SNAPSHOT.jar",
          "url": "jason-2.6.3-SNAPSHOT.jar",
          "size": 1156158,
          "sha512": "10626e38366c46f8240ea92d46f0fb7872d8bf11ab9c8c11a9f57c90bc04bef4a56cfb446252fc104884c9da157cad2eeeac6e0efe496666cc99122ff1b8e298",
          "sha256": "fdd82c6db40154d2fee81cad24b68f4c152a12b0795016116933838b0c467de6",
          "sha1": "fd6be0754948c82f6d1e85cad2639728fdcdee84",
          "md5": "b49d85b07c6b47fa9fa93dc3ed82353e"
        }
      ]
    }
  ]
}
