{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-rest",
    "version": "0.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.9-SNAPSHOT.jar",
          "url": "jacamo-rest-0.9-SNAPSHOT.jar",
          "size": 57690,
          "sha512": "1e26fdea1f63e6a24f4b6a95e9b9709bca6d69c0536292ec7efd0e3e3ccdece9283d482bbe3e1c90dcbcb90c005478e291fc9b49a1de23d01580e4b540aca523",
          "sha256": "fa00bc7efa4702651ee3ed603dd1712391fdb9ffbed95a53357aae63a3dc9848",
          "sha1": "3db76c188c08a38ef67ad3b37f5424040ea15a76",
          "md5": "ba9f676d2e0c4afadee09ee007f4e9fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.9-SNAPSHOT.jar",
          "url": "jacamo-rest-0.9-SNAPSHOT.jar",
          "size": 57690,
          "sha512": "1e26fdea1f63e6a24f4b6a95e9b9709bca6d69c0536292ec7efd0e3e3ccdece9283d482bbe3e1c90dcbcb90c005478e291fc9b49a1de23d01580e4b540aca523",
          "sha256": "fa00bc7efa4702651ee3ed603dd1712391fdb9ffbed95a53357aae63a3dc9848",
          "sha1": "3db76c188c08a38ef67ad3b37f5424040ea15a76",
          "md5": "ba9f676d2e0c4afadee09ee007f4e9fb"
        }
      ]
    }
  ]
}
