{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.10"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.3.0.jar",
          "url": "jacamo-1.3.0.jar",
          "size": 602289,
          "sha512": "6c587d0de3f41291f51f805e511020b9b4b48c82890891012d48dbfdc6df935625deefb6eefdbe9201fd489c8afcd2035ee4098ea7a91d373ac700453d3e0336",
          "sha256": "ff430dc5d7ef2f7f923bb24017cd76fca3df240703aba0965914adb68d3fb30a",
          "sha1": "f5b8f593d9393a9166d8945204f277de49c6010f",
          "md5": "8d7b0e36493d5defffb5c07fcd05dfee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.10"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.3.0.jar",
          "url": "jacamo-1.3.0.jar",
          "size": 602289,
          "sha512": "6c587d0de3f41291f51f805e511020b9b4b48c82890891012d48dbfdc6df935625deefb6eefdbe9201fd489c8afcd2035ee4098ea7a91d373ac700453d3e0336",
          "sha256": "ff430dc5d7ef2f7f923bb24017cd76fca3df240703aba0965914adb68d3fb30a",
          "sha1": "f5b8f593d9393a9166d8945204f277de49c6010f",
          "md5": "8d7b0e36493d5defffb5c07fcd05dfee"
        }
      ]
    }
  ]
}
