{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.2.jar",
          "url": "jacamo-1.2.jar",
          "size": 616585,
          "sha512": "ce162cc2797520c634b5ac81d9c2c6d55e1fb61ae5e3bd6a5923de17fd16b45ed613b3755d74efd8626920736db35f7c7d484400d52b6a69131e232cc144e437",
          "sha256": "4ed3aa50ad58f2af85e77ffeaed38bcc14cdda0ffb45f53642eeaef6c1aa3cff",
          "sha1": "d07e72a418f95732440aeafd01d50ec30cb8a19f",
          "md5": "afccef8154b1501e99fbdf9d4f46ed6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.2.jar",
          "url": "jacamo-1.2.jar",
          "size": 616585,
          "sha512": "ce162cc2797520c634b5ac81d9c2c6d55e1fb61ae5e3bd6a5923de17fd16b45ed613b3755d74efd8626920736db35f7c7d484400d52b6a69131e232cc144e437",
          "sha256": "4ed3aa50ad58f2af85e77ffeaed38bcc14cdda0ffb45f53642eeaef6c1aa3cff",
          "sha1": "d07e72a418f95732440aeafd01d50ec30cb8a19f",
          "md5": "afccef8154b1501e99fbdf9d4f46ed6a"
        }
      ]
    }
  ]
}
