{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "qqglgr774vamdgn4eqjmzgsvsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.0-SNAPSHOT.jar",
          "url": "jason-3.0-SNAPSHOT.jar",
          "size": 1186707,
          "sha512": "a7d7c068077808df3cac5d922ebb9f0b3127aaa4f4fb221a81135f39284cb8db3a91a2ea562df6a7b2bb8c2d7d2c56b816bd9cd55c567b3a70a457ba59de4145",
          "sha256": "7c0c92471fdb2044823a0229c500d8cb71d5303b1e8fab43ca274e17546cbc90",
          "sha1": "9f95b4cf9fe9649617fdead4d96fed2fe9c5648b",
          "md5": "3d442d33c42df5c2f4e4afbc0c3926e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.0-SNAPSHOT.jar",
          "url": "jason-3.0-SNAPSHOT.jar",
          "size": 1186707,
          "sha512": "a7d7c068077808df3cac5d922ebb9f0b3127aaa4f4fb221a81135f39284cb8db3a91a2ea562df6a7b2bb8c2d7d2c56b816bd9cd55c567b3a70a457ba59de4145",
          "sha256": "7c0c92471fdb2044823a0229c500d8cb71d5303b1e8fab43ca274e17546cbc90",
          "sha1": "9f95b4cf9fe9649617fdead4d96fed2fe9c5648b",
          "md5": "3d442d33c42df5c2f4e4afbc0c3926e6"
        }
      ]
    }
  ]
}
