{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "k34dlk3vbbbojgwhrerwxnxsc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.0-SNAPSHOT.jar",
          "url": "jason-3.0-SNAPSHOT.jar",
          "size": 1192296,
          "sha512": "5ee5c44a821eb342361697c508fc32ea7f2e2228cecc56cf9202915382ea0984a05eacd8c769ad78e0540241973a45caf15c910ff5f8a8b1c49c78c72f34bf1d",
          "sha256": "0eefc66d662836835c8bd82807d9d8eb94cba6cc4fb842216d7538c68dc905ef",
          "sha1": "fc515a1c61858efa1f7afc2fd53820b2e124f9b3",
          "md5": "bcdabcab3b2d51e7693c0efc73e34bd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.0-SNAPSHOT.jar",
          "url": "jason-3.0-SNAPSHOT.jar",
          "size": 1192296,
          "sha512": "5ee5c44a821eb342361697c508fc32ea7f2e2228cecc56cf9202915382ea0984a05eacd8c769ad78e0540241973a45caf15c910ff5f8a8b1c49c78c72f34bf1d",
          "sha256": "0eefc66d662836835c8bd82807d9d8eb94cba6cc4fb842216d7538c68dc905ef",
          "sha1": "fc515a1c61858efa1f7afc2fd53820b2e124f9b3",
          "md5": "bcdabcab3b2d51e7693c0efc73e34bd4"
        }
      ]
    }
  ]
}
