{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason",
    "module": "jason",
    "version": "3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "y5ib6wwsurdkxacwm4yfgwthda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.0-SNAPSHOT.jar",
          "url": "jason-3.0-SNAPSHOT.jar",
          "size": 1191019,
          "sha512": "147a374c19eb4ffa3ab94ac3f9482025064ec960e822975d3a3f6cc2f59d135575867a66c54170ea53c1e1f3990f3cdd3e641ef6973343ce75d0d3c96b361f68",
          "sha256": "7925386f65d9315c172ba1337c0232eaa7f744a6f6928ef1327b6b0930dfa727",
          "sha1": "24aa7bd0fa12d955867f74f2f5ef809227f1a360",
          "md5": "83fe4474fd4c47142b1944b64e3949b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "jason-3.0-SNAPSHOT.jar",
          "url": "jason-3.0-SNAPSHOT.jar",
          "size": 1191019,
          "sha512": "147a374c19eb4ffa3ab94ac3f9482025064ec960e822975d3a3f6cc2f59d135575867a66c54170ea53c1e1f3990f3cdd3e641ef6973343ce75d0d3c96b361f68",
          "sha256": "7925386f65d9315c172ba1337c0232eaa7f744a6f6928ef1327b6b0930dfa727",
          "sha1": "24aa7bd0fa12d955867f74f2f5ef809227f1a360",
          "md5": "83fe4474fd4c47142b1944b64e3949b7"
        }
      ]
    }
  ]
}
