{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5-SNAPSHOT.jar",
          "url": "sai-0.5-SNAPSHOT.jar",
          "size": 318397,
          "sha512": "f8cb40d15898be7230f1f808ddb9392f626c55d81d1fae7f18ecc4bed5ea4adf0c58f4dba687627d22ec7bf2f4ed6e21d2ae7a090129bccbe130638184ad8681",
          "sha256": "b1de71b553a834bc688a3210bf3ff6b38f1838aaaa83f69c24589804c95fa912",
          "sha1": "b0c2ee19c509427f6e89388dd681b46ac2b71e09",
          "md5": "ef46ae96ae0b80073d27004657112227"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5-SNAPSHOT.jar",
          "url": "sai-0.5-SNAPSHOT.jar",
          "size": 318397,
          "sha512": "f8cb40d15898be7230f1f808ddb9392f626c55d81d1fae7f18ecc4bed5ea4adf0c58f4dba687627d22ec7bf2f4ed6e21d2ae7a090129bccbe130638184ad8681",
          "sha256": "b1de71b553a834bc688a3210bf3ff6b38f1838aaaa83f69c24589804c95fa912",
          "sha1": "b0c2ee19c509427f6e89388dd681b46ac2b71e09",
          "md5": "ef46ae96ae0b80073d27004657112227"
        }
      ]
    }
  ]
}
