{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5-SNAPSHOT.jar",
          "url": "sai-0.5-SNAPSHOT.jar",
          "size": 318425,
          "sha512": "6d2e47f3598687d7826fe06877f578766909e12e5ecc4658ed7ecb682e2f7bf8d8f4e3345ee69d63c1fee9ca9c281cbe0c4bab50fa40a4275254157124d77f9e",
          "sha256": "39300939a6797a45486001c914ac8f942f68fbe79bee389cc06e649229b17edb",
          "sha1": "d139fab9085a762b8bc1d9b549b2629a8d7fa8e5",
          "md5": "e3d03f7190b1ba9b17eb21bb61623b00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5-SNAPSHOT.jar",
          "url": "sai-0.5-SNAPSHOT.jar",
          "size": 318425,
          "sha512": "6d2e47f3598687d7826fe06877f578766909e12e5ecc4658ed7ecb682e2f7bf8d8f4e3345ee69d63c1fee9ca9c281cbe0c4bab50fa40a4275254157124d77f9e",
          "sha256": "39300939a6797a45486001c914ac8f942f68fbe79bee389cc06e649229b17edb",
          "sha1": "d139fab9085a762b8bc1d9b549b2629a8d7fa8e5",
          "md5": "e3d03f7190b1ba9b17eb21bb61623b00"
        }
      ]
    }
  ]
}
