{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "sai",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5vkxjqndbjdqtn3yk7u27x5jja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5-SNAPSHOT.jar",
          "url": "sai-0.5-SNAPSHOT.jar",
          "size": 317780,
          "sha512": "007b7327afd6f2bfd806de2cfeac0c6e0ae788d9928aacf02d53325a1284e70e39efaa24a34fda683f133d1092820b1c0743504b3f8b616373dad6020659c846",
          "sha256": "de1ae4ad6b064166cf6134cf180b37bbd1360ce6941c1e886c517458dcc9b1c1",
          "sha1": "0f0fc0f85fdf6d99467108225b10bbbddee7a418",
          "md5": "e71304518e6b4fd2cbf54b48c9994fe4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.8"
          }
        }
      ],
      "files": [
        {
          "name": "sai-0.5-SNAPSHOT.jar",
          "url": "sai-0.5-SNAPSHOT.jar",
          "size": 317780,
          "sha512": "007b7327afd6f2bfd806de2cfeac0c6e0ae788d9928aacf02d53325a1284e70e39efaa24a34fda683f133d1092820b1c0743504b3f8b616373dad6020659c846",
          "sha256": "de1ae4ad6b064166cf6134cf180b37bbd1360ce6941c1e886c517458dcc9b1c1",
          "sha1": "0f0fc0f85fdf6d99467108225b10bbbddee7a418",
          "md5": "e71304518e6b4fd2cbf54b48c9994fe4"
        }
      ]
    }
  ]
}
