{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.9-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.3.1.jar",
          "url": "jacamo-1.3.1.jar",
          "size": 579371,
          "sha512": "f6808cae212e0a5514528bfc898c1c1c76c0db954b3098f3f00b5f158135b1bd2d81337f20369c33c488fe42139e748dcfbb68376944ca3712a2b2a4ec58d204",
          "sha256": "a52869979268e5256ea82861dc180cddb1d6d84fc5230e4de6288fa26ebc5705",
          "sha1": "6e3d0a93ba2fe27f83bd0b373db70cf31bf26ba3",
          "md5": "744c9150a84ec24d5099f2e86d3f8a3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j2-impl",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.9-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.3.1.jar",
          "url": "jacamo-1.3.1.jar",
          "size": 579371,
          "sha512": "f6808cae212e0a5514528bfc898c1c1c76c0db954b3098f3f00b5f158135b1bd2d81337f20369c33c488fe42139e748dcfbb68376944ca3712a2b2a4ec58d204",
          "sha256": "a52869979268e5256ea82861dc180cddb1d6d84fc5230e4de6288fa26ebc5705",
          "sha1": "6e3d0a93ba2fe27f83bd0b373db70cf31bf26ba3",
          "md5": "744c9150a84ec24d5099f2e86d3f8a3e"
        }
      ]
    }
  ]
}
