{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.9-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.3.1.jar",
          "url": "jacamo-1.3.1.jar",
          "size": 579332,
          "sha512": "1eaa3561f6da546561b3f762b9c6dba70a9dbe96b42c4e461fe3500eab630b5a001e8288543eaf42178697a6fcdbd832b6b8dae566ec385106b7be49c1e95836",
          "sha256": "8bd3dafa193e67625f8b84ee3ee5d143be0202b5352c1024ba4a87e9399f8180",
          "sha1": "d69ebbb6d85463ca2dc7d3e246d3f9386cd459e6",
          "md5": "0eb296973497799dcc346da7aae0485d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sync",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-unit",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web-client",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "moise",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "intmas",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "sai",
          "version": {
            "requires": "0.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.9-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jacamo",
              "module": "jacamo"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-1.3.1.jar",
          "url": "jacamo-1.3.1.jar",
          "size": 579332,
          "sha512": "1eaa3561f6da546561b3f762b9c6dba70a9dbe96b42c4e461fe3500eab630b5a001e8288543eaf42178697a6fcdbd832b6b8dae566ec385106b7be49c1e95836",
          "sha256": "8bd3dafa193e67625f8b84ee3ee5d143be0202b5352c1024ba4a87e9399f8180",
          "sha1": "d69ebbb6d85463ca2dc7d3e246d3f9386cd459e6",
          "md5": "0eb296973497799dcc346da7aae0485d"
        }
      ]
    }
  ]
}
