{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-web",
    "version": "0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-web-0.7-SNAPSHOT.jar",
          "url": "jacamo-web-0.7-SNAPSHOT.jar",
          "size": 2994662,
          "sha512": "1ba6943f2748626905a7dc0f200a7c2dd879033fa3e8c5e6921c5cf2cc2dc831c90eb3940377f5c9423dccb562b18ac1634cf78dfd3876a6ee361c3ed4e72037",
          "sha256": "f5fddcb214287d81c882ad0174c2636851ccc7f9c8008edee55ee64f69476035",
          "sha1": "f99a73f836beffb3fd5e935ceab61d6770a771d5",
          "md5": "e09a29f176430d36fdd79b4a23a03a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.zookeeper",
          "module": "zookeeper",
          "version": {
            "requires": "3.5.4-beta"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-framework",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "javax.websocket",
          "module": "javax.websocket-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-server",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-container-grizzly",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.6.0.201912101111-r"
          }
        },
        {
          "group": "net.openhft",
          "module": "compiler",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-web-0.7-SNAPSHOT.jar",
          "url": "jacamo-web-0.7-SNAPSHOT.jar",
          "size": 2994662,
          "sha512": "1ba6943f2748626905a7dc0f200a7c2dd879033fa3e8c5e6921c5cf2cc2dc831c90eb3940377f5c9423dccb562b18ac1634cf78dfd3876a6ee361c3ed4e72037",
          "sha256": "f5fddcb214287d81c882ad0174c2636851ccc7f9c8008edee55ee64f69476035",
          "sha1": "f99a73f836beffb3fd5e935ceab61d6770a771d5",
          "md5": "e09a29f176430d36fdd79b4a23a03a8b"
        }
      ]
    }
  ]
}
