{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-web",
    "version": "0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jacamo-web-0.7-SNAPSHOT.jar",
          "url": "jacamo-web-0.7-SNAPSHOT.jar",
          "size": 2992945,
          "sha512": "5656cd53568459469a43c950390dd9b1edf6cfe1dc03837936d7fdedc38aef37eb8f064027c0f80a5c7874b36c51870dcf344fad3ef978d9be3bf2716d647a08",
          "sha256": "4b1f66c760c59246a2f74c18bdaa70f3e9a8fbc4af919f0a1b4194ae8f0d5290",
          "sha1": "e0f2a279916ffe042cdbed30492c17583215fee4",
          "md5": "1c7806d042dcc0e322c83c68be99aac1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo-rest",
          "version": {
            "requires": "0.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.apache.zookeeper",
          "module": "zookeeper",
          "version": {
            "requires": "3.5.4-beta"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-framework",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "javax.websocket",
          "module": "javax.websocket-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-server",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-container-grizzly",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.6.0.201912101111-r"
          }
        },
        {
          "group": "net.openhft",
          "module": "compiler",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-web-0.7-SNAPSHOT.jar",
          "url": "jacamo-web-0.7-SNAPSHOT.jar",
          "size": 2992945,
          "sha512": "5656cd53568459469a43c950390dd9b1edf6cfe1dc03837936d7fdedc38aef37eb8f064027c0f80a5c7874b36c51870dcf344fad3ef978d9be3bf2716d647a08",
          "sha256": "4b1f66c760c59246a2f74c18bdaa70f3e9a8fbc4af919f0a1b4194ae8f0d5290",
          "sha1": "e0f2a279916ffe042cdbed30492c17583215fee4",
          "md5": "1c7806d042dcc0e322c83c68be99aac1"
        }
      ]
    }
  ]
}
