{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "npl",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6.1.jar",
          "url": "npl-0.6.1.jar",
          "size": 90772,
          "sha512": "7000605dabe014b2b33d94d5b7ce17efe2975d7abeb3026a71172bb44589cdd60d123071fc755088d86713bdce6f2a3aeabd9c6779d21e87dfffa1d32a8d5e05",
          "sha256": "d1a559ac83d9b360bcdc75adf3d9c0d6c5c83b229e1ed9bc2c0a612a286250e0",
          "sha1": "b60311f7a215e69915a08379f187643f440bb340",
          "md5": "2f3bc15186968deb4fe0c9cf6a5c0308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6.1.jar",
          "url": "npl-0.6.1.jar",
          "size": 90772,
          "sha512": "7000605dabe014b2b33d94d5b7ce17efe2975d7abeb3026a71172bb44589cdd60d123071fc755088d86713bdce6f2a3aeabd9c6779d21e87dfffa1d32a8d5e05",
          "sha256": "d1a559ac83d9b360bcdc75adf3d9c0d6c5c83b229e1ed9bc2c0a612a286250e0",
          "sha1": "b60311f7a215e69915a08379f187643f440bb340",
          "md5": "2f3bc15186968deb4fe0c9cf6a5c0308"
        }
      ]
    }
  ]
}
