{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "npl",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6.1.jar",
          "url": "npl-0.6.1.jar",
          "size": 91153,
          "sha512": "9c1e13d8133af6fff962a2210c99424a2ac5868c687d5ff15b7b642fad51446c8d892fcdbd38aa22e1c96f7156d83cecd17edfc8169310cecb8d4dde926327cb",
          "sha256": "956818edfe9aeff7c4fde35bf1dd276cd71e1da62daf77a2a15ab08f87903332",
          "sha1": "77764947cbb616a36ca892954050de7ca0d92043",
          "md5": "b6919a3134ccd4a25a88ade389e3110f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          },
          "excludes": [
            {
              "group": "net.sf.ingenias",
              "module": "jade"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "npl-0.6.1.jar",
          "url": "npl-0.6.1.jar",
          "size": 91153,
          "sha512": "9c1e13d8133af6fff962a2210c99424a2ac5868c687d5ff15b7b642fad51446c8d892fcdbd38aa22e1c96f7156d83cecd17edfc8169310cecb8d4dde926327cb",
          "sha256": "956818edfe9aeff7c4fde35bf1dd276cd71e1da62daf77a2a15ab08f87903332",
          "sha1": "77764947cbb616a36ca892954050de7ca0d92043",
          "md5": "b6919a3134ccd4a25a88ade389e3110f"
        }
      ]
    }
  ]
}
