{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.0.jar",
          "url": "jason-interpreter-3.2.0.jar",
          "size": 1117339,
          "sha512": "3f7068d1bafa93fc6361f20959a5319a6ac4ee6139b6e516122001f093f2e66a23f899d1375c46bec92f3f2c003fd14945a4b719748d27066a681b8851296be7",
          "sha256": "ca0d27308189ad485d7b934cd98e6f95ec80baf0ac98c9125a3b3caed01d8faa",
          "sha1": "d634b0f8fb5421383d7115680fde2f41aa5cfa42",
          "md5": "0a0bbbb9308dcd26fc51c4fdf3537583"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.0.jar",
          "url": "jason-interpreter-3.2.0.jar",
          "size": 1117339,
          "sha512": "3f7068d1bafa93fc6361f20959a5319a6ac4ee6139b6e516122001f093f2e66a23f899d1375c46bec92f3f2c003fd14945a4b719748d27066a681b8851296be7",
          "sha256": "ca0d27308189ad485d7b934cd98e6f95ec80baf0ac98c9125a3b3caed01d8faa",
          "sha1": "d634b0f8fb5421383d7115680fde2f41aa5cfa42",
          "md5": "0a0bbbb9308dcd26fc51c4fdf3537583"
        }
      ]
    }
  ]
}
