{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.2.jar",
          "url": "jason-interpreter-3.2.2.jar",
          "size": 1085647,
          "sha512": "bd786d4738735c75988ac24035c93803a8b0d3a12909a72aee656c83cee59bf38002e516d811bfb0be91c91563b13e7ee94c06c33b263e5e4f45e2802d8832a6",
          "sha256": "3ebbeeda246f5d02d77e10119c313d10db55d11c1553f801de7063f81b4fc1d0",
          "sha1": "4c509f75535b67280a34135babd62e218ad46fcb",
          "md5": "91b052827060fd7943b397ff64c2f78d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.2.jar",
          "url": "jason-interpreter-3.2.2.jar",
          "size": 1085647,
          "sha512": "bd786d4738735c75988ac24035c93803a8b0d3a12909a72aee656c83cee59bf38002e516d811bfb0be91c91563b13e7ee94c06c33b263e5e4f45e2802d8832a6",
          "sha256": "3ebbeeda246f5d02d77e10119c313d10db55d11c1553f801de7063f81b4fc1d0",
          "sha1": "4c509f75535b67280a34135babd62e218ad46fcb",
          "md5": "91b052827060fd7943b397ff64c2f78d"
        }
      ]
    }
  ]
}
