{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-interpreter",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.2.jar",
          "url": "jason-interpreter-3.2.2.jar",
          "size": 1085628,
          "sha512": "5a8752c124672508e87b9a9b06386289c7a80ee6bbd8e7fb72964a8013eaddc35f16bc7a0b2e0327eda4f2e27b6781802346f865bdff32d46f206032f887e376",
          "sha256": "694fd9ae4a86a79d573b4bcf5a61729d0aee76bc2e6ecd6c7cb57b02a655327d",
          "sha1": "476e51ab7e1bd6de12650c3bf72480ffe2d3a2ac",
          "md5": "adba777926731b7561e7bef1d965ea59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.ingenias",
          "module": "jade",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "jason-interpreter-3.2.2.jar",
          "url": "jason-interpreter-3.2.2.jar",
          "size": 1085628,
          "sha512": "5a8752c124672508e87b9a9b06386289c7a80ee6bbd8e7fb72964a8013eaddc35f16bc7a0b2e0327eda4f2e27b6781802346f865bdff32d46f206032f887e376",
          "sha256": "694fd9ae4a86a79d573b4bcf5a61729d0aee76bc2e6ecd6c7cb57b02a655327d",
          "sha1": "476e51ab7e1bd6de12650c3bf72480ffe2d3a2ac",
          "md5": "adba777926731b7561e7bef1d965ea59"
        }
      ]
    }
  ]
}
