{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jason-lang",
    "module": "jason-cli",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli-shell-jline3",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.10"
          }
        }
      ],
      "files": [
        {
          "name": "jason-cli-3.3.1.jar",
          "url": "jason-cli-3.3.1.jar",
          "size": 58145,
          "sha512": "948a758f0eb35a89ec804708e73a0b6f389d4395b52c66f5d58b3ae675bde931519cee0503a6e4c1b83c969e60a244e62c2845f8595289ffa041e14293064342",
          "sha256": "d67200d75fb80643a85634b2c13b60e76f2a1f8f4bf1c6f3891aaff1340cb6c8",
          "sha1": "4ddddb2a49031e5cb96d4f98d5aa6201b2e4acde",
          "md5": "512b1082ce80a3d517c73d7c3e6c2e54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli-shell-jline3",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "8.10"
          }
        }
      ],
      "files": [
        {
          "name": "jason-cli-3.3.1.jar",
          "url": "jason-cli-3.3.1.jar",
          "size": 58145,
          "sha512": "948a758f0eb35a89ec804708e73a0b6f389d4395b52c66f5d58b3ae675bde931519cee0503a6e4c1b83c969e60a244e62c2845f8595289ffa041e14293064342",
          "sha256": "d67200d75fb80643a85634b2c13b60e76f2a1f8f4bf1c6f3891aaff1340cb6c8",
          "sha1": "4ddddb2a49031e5cb96d4f98d5aa6201b2e4acde",
          "md5": "512b1082ce80a3d517c73d7c3e6c2e54"
        }
      ]
    }
  ]
}
