{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "jacamo-rest",
    "version": "0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.8.jar",
          "url": "jacamo-rest-0.8.jar",
          "size": 58784,
          "sha512": "d4a46102d6e71d473b491c84cb42cf8826ec9453f248b7633f04d9d7e669a576cb580bd6f4ac40be5fcfec39f0e4c9d33b5bda32c19fb5fbad8161940540a35e",
          "sha256": "8983bb4f58320c2ff103dc6b688572f934ea2bb050dca913298396069a076dd6",
          "sha1": "7b296b024728d43b0bbfbd5db9ed9ede7ba05252",
          "md5": "5fd58f254abcfebfdf73cd3c509f013f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-core",
          "version": {
            "requires": "2.3.0.1"
          }
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-nop"
            }
          ]
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-servlet-core",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.inject",
          "module": "jersey-hk2",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey",
          "module": "jersey-bom",
          "version": {
            "requires": "2.29.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jersey-bom",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-server",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.core",
          "module": "jersey-client",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-json-jackson",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.jersey.containers",
          "module": "jersey-container-grizzly2-http",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.glassfish.grizzly",
          "module": "grizzly-http-server",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "jacamo-rest-0.8.jar",
          "url": "jacamo-rest-0.8.jar",
          "size": 58784,
          "sha512": "d4a46102d6e71d473b491c84cb42cf8826ec9453f248b7633f04d9d7e669a576cb580bd6f4ac40be5fcfec39f0e4c9d33b5bda32c19fb5fbad8161940540a35e",
          "sha256": "8983bb4f58320c2ff103dc6b688572f934ea2bb050dca913298396069a076dd6",
          "sha1": "7b296b024728d43b0bbfbd5db9ed9ede7ba05252",
          "md5": "5fd58f254abcfebfdf73cd3c509f013f"
        }
      ]
    }
  ]
}
